trial_name : rich
mo_vae_ckpt_path : "/is/ps3/nsaini/projects/mcms/mcms_logs/2022_03_07/v000_/checkpoints/epoch:2099-step:125999.ckpt"
data_path : "/home/nsaini/Datasets/opencam/20220417/Niz_dance"

batch_size : 1
seq_len : 25
loss_2d_weight : 1
loss_z_weight : 5
loss_cams_weight : 1000
loss_betas_weight : 100
n_optim_iters_stage1: 1000
n_optim_iters : 2000
loss_human_gp_weight : 1000
loss_smpl_in_front_weight : 1000
loss_cam_gp_weight : 100
loss_vp_weight : 0
lr : 0.05

dset : "rich"
use_pare_init : True

seq_no : 29
big_seq_start : 0
big_seq_end : 614
overlap : 5

position_changing_cams : [7]
orient_changing_cams : [7]
optimize_intr : false