# path to mop data directory
mop_data : "mop_data/checkpoints/epoch=869-step=275789.ckpt"

# path to neutral SMPL body model .npz file
bm_fname : "/home/nsaini/Datasets/smpl_models/smplh/neutral/model.npz"
# bm_fname : "/home/nsaini/Datasets/smpl_models/smpl/SMPL_NEUTRAL.pkl"

# type of dataset (one of {rich, copenet_real, savitr})
dset : "rich"

# data_path : "/ps/project/datasets/AirCap_ICCV19/opencam/VolleyDay"
# data_path : "/ps/project/datasets/AirCap_ICCV19/opencam/20220417/Niz_dance"
# data_path : "/ps/project/datasets/AirCap_ICCV19/RICH_IPMAN/val/2021-06-15_Multi_IOI_ID_00228_Yoga1"
# data_path : "/ps/project/datasets/AirCap_ICCV19/RICH_IPMAN/val/2021-06-15_Multi_IOI_ID_03588_Yoga1"
# data_path : "/ps/project/datasets/AirCap_ICCV19/copenet_data_local_machine/copenet_data"

# path to the dataset root directory
data_path : "/ps/project/datasets/AirCap_ICCV19/RICH_IPMAN/test/2021-06-15_Multi_IOI_ID_00186_Yoga1"

# vposer model v2.0 path
vposer_path : "/ps/scratch/common/vposer/V02_05"

batch_size : 1
mop_seq_len : 25
loss_2d_weight : [1,1,1]
loss_z_weight : [10,10,10]
loss_j3d_smooth_weight: [1,1,0.1]
loss_cams_orient_weight : [1,1,1]
loss_cams_position_weight : [100000,100000,100000]
loss_betas_weight : [100,100,100]
loss_cont_weight: [100,100,100]
n_optim_iters: [[2000,3000,4000],[0,0,2000]]
loss_human_gp_weight : [1.0e4,1.0e4,1.0e4]
loss_smpl_in_front_weight : [0,0,0]
loss_cam_gp_weight : [1.0e4,1.0e4,1.0e4]
loss_vp_weight : [10,10,10]
gmcclure_sigma : 40
lr : [0.01,0.001,0.001]

use_pare_init : True

seq_no : 29
big_seq_start : 6
big_seq_end : 581
overlap : 2
init_seq_len : 25
stitch_len : -1

# List of cameras to be used
cams_used : [0,1,2,3,4,5,6,7]
# List of cameras with dynamic position
position_changing_cams : [7]
# List of cameras with dynamic orientation
orient_changing_cams : [7]
# If optimize for intrinsics
optimize_intr : false
# Device (keep it cpu)
device: "cpu"