batch_size: 1
big_seq_end: 2000
big_seq_start: 1450
bm_fname: # Fill the body model path
cams_used:
- 0
- 1
- 2
- 3
data_path: # Fill the data path
device: cpu
dset: savitr
gmcclure_sigma: 40
init_seq_len: 25
loss_2d_weight:
- 1
- 1
- 1
loss_betas_weight:
- 100
- 100
- 100
loss_cam_gp_weight:
- 1.0e4
- 1.0e4
- 1.0e4
loss_cams_orient_weight:
- 1
- 1
- 1
loss_cams_position_weight:
- 100000
- 100000
- 100000
loss_cont_weight:
- 100
- 100
- 100
loss_human_gp_weight:
- 1.0e4
- 1.0e4
- 1.0e4
loss_j3d_smooth_weight:
- 1
- 1
- 0.5
loss_smpl_in_front_weight:
- 0
- 0
- 0
loss_vp_weight:
- 10
- 10
- 10
loss_z_weight:
- 10
- 10
- 10
lr:
- 0.01
- 0.001
- 0.001
mop_data: # Fill the MOP data directory path
n_optim_iters:
- - 2000
  - 3000
  - 4000
- - 0
  - 0
  - 1000
nmg_seq_len: 25
optimize_intr: false
orient_changing_cams:
- 0
- 1
overlap: 10
position_changing_cams:
- 0
- 1
seq_no: '0'
stitch_len: -1
use_pare_init: true